# Generated by Django 3.0.8 on 2020-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
