# Generated by Django 3.0.8 on 2020-07-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_is_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='frequency',
            field=models.IntegerField(choices=[('No', 'None'), ('Da', 'Daily'), ('Wk', 'Weekly'), ('Bi', 'Biweekly'), ('Mo', 'Monthly')]),
        ),
    ]
