# Generated by Django 3.0.8 on 2020-07-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20200725_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Daily'), (7, 'Weekly'), (14, 'Biweekly'), (30, 'Monthly')]),
        ),
    ]
