# Generated by Django 3.0.8 on 2020-07-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200725_1551'),
        ('menus', '0004_auto_20200725_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount_due', models.FloatField(default=0.0)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('oustanding', models.FloatField(default=0.0)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('preparing', 'Preparing'), ('completed', 'Completed')], default='created', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
                ('items_ordered', models.ManyToManyField(to='menus.Menu')),
                ('vendor', models.ManyToManyField(to='users.Vendor')),
            ],
        ),
    ]
